site_name: Aaron Currie
site_url: https://aacurrie.github.io/aacurrie-blog
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.expand
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  language: en
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue grey
      toggle:
          icon: material/toggle-switch
          name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: light red
      toggle:
          icon: material/toggle-switch-off-outline
          name: Switch to dark mode

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/aacurrie
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/aaron-a-currie

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - blog

copyright: |
  &copy; 2024 <a href="https://github.com/aacurrie"  target="_blank" rel="noopener">Aaron Currie</a>